### ISSUE TITLE
Support Tez Metrics

### ISSUE THREAD

**Issue by vrajat** [qubole/dr-elephant#4]

**Comment by murthykurra** [comment]
Hi All,

Do we need to change all the parameters given by you or inside app-conf and app directories is enough.

Thanks in advance

**Comment by murthykurra** [comment]
one more is do we need to install any softwares to do this
like quablo

**Comment by murthykurra** [comment]
Hi All

Where we can find the below value
sbt release -Daws.accessKeyId=XXXXXX -Daws.secretKey=XXXXXX

Thanks in advance.

**Comment by vrajat** [comment]
Hi @murthykurra

The jars of Qubole's Dr. Elephant fork is available at `s3://maven-qubole/release/com/linkedin/drelephant/dr-elephant_2.10/2.0.6-qds-0.5.0/`. You can pick up the jars from here. 

Alternatively (and this is the preferred method), follow the instructions from https://github.com/linkedin/dr-elephant/wiki/Quick-Setup-Instructions

with the following changes in Step 1:

    git clone https://github.com/qubole/dr-elephant
    cd dr-elephant
    git co q-master

You dont need to run any other software or any Qubole specific services. Please contact us if you have any specific questions on Tez support.

**Comment by murthykurra** [comment]
Hi 

Thanks for update.
but while compiling ./compile.sh we are getting below error.

downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.13/jars/cache.jar ...
        [SUCCESSFUL ] org.scala-sbt#cache;0.13.13!cache.jar (1205ms)
downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.13/jars/test-agent.jar ...
        [SUCCESSFUL ] org.scala-sbt#test-agent;0.13.13!test-agent.jar (1201ms)
downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.13/jars/apply-macro.jar ...
        [SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.13!apply-macro.jar (1392ms)
downloading http://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar ...
        [SUCCESSFUL ] org.scala-sbt#template-resolver;0.1!template-resolver.jar (130ms)
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        50 artifacts copied, 0 already retrieved (17645kB/37ms)
Getting Scala 2.10.3 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
        confs: [default]
        5 artifacts copied, 0 already retrieved (24447kB/22ms)
java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
        at scala.reflect.internal.util.Position.start(Position.scala:114)
        at sbt.internals.parser.SbtParser.sbt$internals$parser$SbtParser$$convertStatement$1(SbtParser.scala:148)
        at sbt.internals.parser.SbtParser$$anonfun$4.apply(SbtParser.scala:153)
        at sbt.internals.parser.SbtParser$$anonfun$4.apply(SbtParser.scala:153)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at sbt.internals.parser.SbtParser.splitExpressions(SbtParser.scala:153)
        at sbt.internals.parser.SbtParser.<init>(SbtParser.scala:58)
        at sbt.EvaluateConfigurations$.splitExpressions(EvaluateConfigurations.scala:226)
        at sbt.EvaluateConfigurations$.parseConfiguration(EvaluateConfigurations.scala:69)
        at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:106)
        at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:775)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:781)
        at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:780)
        at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
        at scala.collection.AbstractMap.getOrElse(Map.scala:58)
        at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:780)
        at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
        at sbt.Load$$anonfun$loadFiles$1$2.apply(Load.scala:788)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at sbt.Load$.loadFiles$1(Load.scala:788)
        at sbt.Load$.discoverProjects(Load.scala:799)
        at sbt.Load$.discover$1(Load.scala:585)
        at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:633)
        at sbt.Load$$anonfun$loadUnit$1.sbt$Load$$anonfun$$loadProjects$1(Load.scala:482)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:485)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.loadUnit(Load.scala:459)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:365)
        at sbt.Load$.loadURI(Load.scala:320)
        at sbt.Load$.load(Load.scala:316)
        at sbt.Load$.load(Load.scala:305)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.apply(Load.scala:146)
        at sbt.Load$.buildPluginDefinition(Load.scala:886)
        at sbt.Load$.buildPlugins(Load.scala:852)
        at sbt.Load$.plugins(Load.scala:840)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$34.apply(Load.scala:465)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:464)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.loadUnit(Load.scala:459)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:365)
        at sbt.Load$.loadURI(Load.scala:320)
        at sbt.Load$.load(Load.scala:316)
        at sbt.Load$.load(Load.scala:305)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.apply(Load.scala:146)
        at sbt.Load$.defaultLoad(Load.scala:39)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:496)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:496)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:488)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.process(State.scala:184)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:57)
        at sbt.xMain.run(Main.scala:29)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
[error] Use 'last' for the full log.

**Comment by murthykurra** [comment]
i am using play 2.2.6 version

**Comment by murthykurra** [comment]
i am using play 2.2.6 version

**Comment by vrajat** [comment]
We've tested with Play 2.2.2. You'll have to try with an older version of Play.

**Comment by murthykurra** [comment]
i have installed play 2.2.2 but still i'm getting the same error .

error:
   at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
        at xsbt.boot.Launch$.run(Launch.scala:57)
        at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
        at xsbt.boot.Launch$.launch(Launch.scala:65)
        at xsbt.boot.Launch$.apply(Launch.scala:16)
        at xsbt.boot.Boot$.runImpl(Boot.scala:32)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.UnsupportedOperationException: Position.start on class scala.reflect.internal.util.OffsetPosition
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? i
[warn] Ignoring load failure: no project loaded.
[error] Not a valid command: clean (similar: last, eval)
[error] clean
[error]      ^

**Comment by murthykurra** [comment]
do we need to change any thing else to compile it

**Comment by murthykurra** [comment]
Thanks for update .

Finally i installed it but we are unable to see tez jobs.

Error:08-23-2017 08:45:09 INFO  [Thread-6] com.linkedin.drelephant.ElephantRunner : Job queue size is 1
08-23-2017 08:45:09 INFO  [dr-el-executor-thread-0] com.linkedin.drelephant.ElephantRunner : Analyzing TEZ application_1503422110037_0011
08-23-2017 08:45:09 ERROR [dr-el-executor-thread-0] com.linkedin.drelephant.ElephantRunner : Index: 0, Size: 0
08-23-2017 08:45:09 ERROR [dr-el-executor-thread-0] com.linkedin.drelephant.ElephantRunner : java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.linkedin.drelephant.tez.TezFetcher.fetchData(TezFetcher.java:57)
        at com.linkedin.drelephant.tez.TezFetcher.fetchData(TezFetcher.java:29)
        at com.linkedin.drelephant.analysis.AnalyticJob.getAnalysis(AnalyticJob.java:231)
        at com.linkedin.drelephant.ElephantRunner$ExecutorJob.run(ElephantRunner.java:177)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


![image](https://user-images.githubusercontent.com/29674056/29616801-39c405a6-8830-11e7-8e2d-6d816313209e.png)

**Comment by murthykurra** [comment]
Please help me to resolve this

**Comment by vrajat** [comment]
This looks like a bug in the code. We havent hit yet. Unfortunately without a reproducer I cant say what could be wrong. The stacktrace mentions where it is broken. Can you look into the data structures and check why the array size is 0 ?

BTW we've also contributed the patch to linkedin project at https://github.com/linkedin/dr-elephant/pull/278

**Comment by murthykurra** [comment]
what files you need 
i will send. please resolve the error.

one more thing is it worked for you?

**Comment by vrajat** [comment]
The problem here is the data returned by the resource manager to dr. elephant. Unfortunately dont see how we can fix this. We dont know how to reproduce the tez app data that is causing the exception. 
This worked for us. We use the fetchers regularly in our stack.
The easiest option is for you to add debug statements, compile and look at the tez application data. Then fix the bug.

**Comment by murthykurra** [comment]
can you elaborate ?
i didn't understand

**Comment by vrajat** [comment]
TezFetcher is crashing because of data returned from your hadoop cluster. So without access to data from your hadoop cluster, we do not have a reproducer. So we cant help you. The fetcher is working with our hadoop clusters.

**Comment by abhishekdas99** [comment]
Can you please make sure your ApplicationHistoryServer is running. Tez fetcher talks to AHS to get all necessary data.
